# Spring Boot configuration
spring:
  application:
    name: screenmatchfrases
  profiles:
    active: ${APP_PROFILE:dev}
# API | Personalization
api:
  profile: ${spring.profiles.active}
  system-tag: LANET-API-SCREENMATCHFRASES
  system-tag-base: SCREENMATCHFRASES.API
  system-version: v.1.0.00
  system-reference: LA.net | API ScreenMatch Frases
  system-information: ScreenMatch Frases
  system-description: ScreenMatch Frases
  system-name: ${api.system-reference} ${api.system-version} (${api.system-tag})
  url-site: www.screenmatchfrases.com
  title-site: SCREENMATCH FRASES
  email-site: contato@screenmatchfrases.com
  config:
    language: pt_BR # en_US
    version: v1
    path: # /api/${api.config.version}
# Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /doc
    enabled: true
    tryItOutEnabled: true